# Build a standalone copy of the syllabus that opens without Jekyll.
#
#   ruby scripts/build_syllabus.rb            # writes handouts/syllabus.html
#   ruby scripts/build_syllabus.rb out.html   # writes somewhere else
#
# The site version (syllabus.html -> _layouts/syllabus.html + _includes/syllabus.html)
# is rendered by GitHub Pages. This script reproduces the same markup from
# _data/units.yml and reuses the CSS from those two templates, so the copy matches
# the site. Links point at the live site. Rerun it whenever units.yml changes.

require "yaml"
require "cgi"

ROOT = File.expand_path("..", __dir__)
BASE = "https://lecy.github.io/econometrics/"
RAW  = "https://github.com/lecy/econometrics/raw/main/"

out_path = ARGV[0] || File.join(ROOT, "handouts", "syllabus.html")

units     = YAML.load_file(File.join(ROOT, "_data/units.yml"))
layout    = File.read(File.join(ROOT, "_layouts/syllabus.html"))
component = File.read(File.join(ROOT, "_includes/syllabus.html"))
front     = YAML.load(File.read(File.join(ROOT, "syllabus.html"))[/\A---\s*\n(.*?)\n---/m, 1])

h   = ->(s) { CGI.escapeHTML(s.to_s) }
url = lambda do |link|
  return RAW + link["url"] if link["raw"]
  link["url"] =~ %r{\Ahttps?://} ? link["url"] : BASE + link["url"]
end

layout_css    = layout[%r{<style>.*?</style>}m]    or abort "no <style> in _layouts/syllabus.html"
component_css = component[%r{<style>.*?</style>}m] or abort "no <style> in _includes/syllabus.html"

parts = units.group_by { |u| u["part"] }

body = +"<div class=\"syl\">\n"
parts.each_with_index do |(part, part_units), i|
  body << %(<h2 class="syl-part" id="syllabus-part-#{i + 1}">#{h[part]}</h2>\n)
  part_units.each do |u|
    abort "unit #{u['id']} has no summary" unless u["summary"]

    lectures = +""
    (u["lectures"] || []).each do |item|
      if item["review"]
        item["links"].each do |l|
          lectures << %(<li><a href="#{url[l]}">#{h[l['label']]}</a><span class="syl-tag">Review</span></li>\n)
        end
      else
        lectures << %(<li><a href="#{url[item['links'].first]}">#{h[item['title']]}</a></li>\n)
      end
    end
    (u["walkthroughs"] || []).each do |item|
      lectures << %(<li><a href="#{url[item['links'].first]}">#{h[item['title']]}</a><span class="syl-tag">R walkthrough</span></li>\n)
    end
    lectures = %(<li class="syl-none">None this unit</li>) if lectures.empty?

    refs = (u["readings"] || []).map do |r|
      cite = r["cite"] ? %(<span class="syl-cite">#{h[r['cite']]}</span>) : ""
      %(<li><a href="#{url[r]}">#{h[r['title']]}</a>#{cite}</li>)
    end.join("\n")
    refs = %(<li class="syl-none">None this unit</li>) if refs.empty?

    body << <<~HTML
      <article class="syl-unit" id="syllabus-#{u['id']}">
        <div class="syl-head">
          <span class="syl-num">Unit #{h[u['number']]}</span>
          <h3 class="syl-title"><a href="#{BASE}##{u['id']}">#{h[u['title']]}</a></h3>
        </div>
        <p class="syl-summary">#{h[u['summary']]}</p>
        <div class="syl-cols">
          <div>
            <p class="syl-label">Lectures</p>
            <ul class="syl-list">
      #{lectures}      </ul>
          </div>
          <div>
            <p class="syl-label">Reference material</p>
            <ul class="syl-list">
      #{refs}
            </ul>
          </div>
        </div>
      </article>
    HTML
  end
end
body << "</div>\n"

nav = parts.keys.each_with_index.map do |part, i|
  %(<a class="part-link" href="#syllabus-part-#{i + 1}">#{h[part.split(' — ').first]}</a>)
end.join

dek = front["dek"] ? %(<p class="dek">#{h[front['dek'].strip]}</p>) : ""

html = <<~HTML
  <!doctype html>
  <html lang="en">
  <head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>#{h[front['title']]} · Applied Econometrics</title>
  <!-- Generated by scripts/build_syllabus.rb from _data/units.yml. Edit the data, then rerun. -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Zilla+Slab:wght@500;600;700&family=Source+Sans+3:ital,wght@0,400;0,600;0,700;1,400&family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;1,8..60,400&display=swap">
  #{layout_css}
  #{component_css}
  </head>
  <body>

  <div class="bar">
    <div class="bar-inner">
      <a class="bar-brand" href="#{BASE}">Applied Econometrics</a>
      <nav class="bar-nav">
        #{nav}
        <a href="#{BASE}">Course archive</a>
        <button type="button" onclick="window.print()">Print</button>
      </nav>
    </div>
  </div>

  <div class="wrap">
    <header class="masthead">
      <p class="eyebrow">Syllabus</p>
      <h1>#{h[front['heading']]}</h1>
      #{dek}
    </header>

  #{body}
  </div>

  </body>
  </html>
HTML

leftover = html.scan(/\{[{%]/).size
abort "unrendered Liquid left in output (#{leftover})" if leftover.positive?

File.write(out_path, html)
puts "wrote #{out_path.sub(ROOT + File::SEPARATOR, '')}: #{units.size} units"
